language: rust

rust: 
    - stable

before_install:
    - sudo apt-get update -qq
    - sudo apt install golang
    - sudo apt install clang

install:
    - sudo apt-get install -y valgrind
    - wget "https://download.libsodium.org/libsodium/releases/libsodium-stable-2018-06-30.tar.gz"
    - tar -xzf libsodium-stable-2018-06-30.tar.gz
    - cd libsodium-stable && ./configure --prefix=/usr && make && sudo make install && cd ..

script: make testgo
